version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1|docker login --username AWS --password-stdin 917377056638.dkr.ecr.us-east-1.amazonaws.com/ecscicd
      - REPOSITORY_URI=917377056638.dkr.ecr.us-east-1.amazonaws.com/ecscicd
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 917377056638.dkr.ecr.us-east-1.amazonaws.com/ecscicd:latest .
      - docker tag 917377056638.dkr.ecr.us-east-1.amazonaws.com/ecscicd:latest 917377056638.dkr.ecr.us-east-1.amazonaws.com/ecscicd:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 917377056638.dkr.ecr.us-east-1.amazonaws.com/ecscicd:latest
      - docker push 917377056638.dkr.ecr.us-east-1.amazonaws.com/ecscicd:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"nodeapp","imageUri":"%s"}]' 917377056638.dkr.ecr.us-east-1.amazonaws.com/ecscicd:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
